# Generated by Django 3.2.9 on 2021-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fasttextmodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='fasttextmodel',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
