# Generated by Django 3.2.9 on 2021-11-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211120_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='fasttextmodel',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
